Algorithms used - 

1.   MLKNN
2.   LogisticRegression

1.   LinearSVC
2.   List item






In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv
Saving train.csv to train.csv


In [ ]:
!pip uninstall scikit-learn -y
!pip install scikit-learn==0.24.1
!pip install scikit-multilearn

Found existing installation: scikit-learn 1.0.1
Uninstalling scikit-learn-1.0.1:
  Successfully uninstalled scikit-learn-1.0.1
     |████████████████████████████████| 22.3 MB 1.6 MB/s 
     |████████████████████████████████| 89 kB 3.5 MB/s 


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from skmultilearn.adapt import MLkNN
from sklearn.metrics import hamming_loss, accuracy_score
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression

In [ ]:
aspects_df = pd.read_csv('train.csv')
aspects_df.head()

Id                                             Review  ...  Usability  Polarity
0   0  For some reason everybody complains and I'm co...  ...          1         0
1   1  I like everything about it, great choice of sp...  ...          0         1
2   2  Excellent ceiling fan brace. Easy to install a...  ...          0         1
3   3  Work great easy to use . No issues at all with...  ...          1         1
4   4  I would recommend this product because it is p...  ...          0         1

[5 rows x 14 columns]

In [ ]:
X = aspects_df["Review"]
y = np.asarray(aspects_df[aspects_df.columns[2:]])
# y = aspects_df[aspects_df.columns[2:]]

# y.head()

In [ ]:
vetorizar = TfidfVectorizer(max_features=3000, max_df=0.85)
vetorizar.fit(X)

TfidfVectorizer(max_df=0.85, max_features=3000)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
X_train_tfidf = vetorizar.transform(X_train)
X_test_tfidf = vetorizar.transform(X_test)

In [ ]:
mlknn_classifier = MLkNN()
mlknn_classifier.fit(X_train_tfidf, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_neighbors=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


MLkNN()

In [ ]:
new_sentences = ["I like the food but I hate the place"]
new_sentence_tfidf = vetorizar.transform(new_sentences)

predicted_sentences = mlknn_classifier.predict(new_sentence_tfidf)
print(predicted_sentences.toarray())

[[0 0 0 0 0 1 0 0 0 0 0 0]]


In [ ]:
predicted = mlknn_classifier.predict(X_test_tfidf)

print(accuracy_score(y_test, predicted))
print(hamming_loss(y_test, predicted))

predicted

0.3219753086419753
0.1017283950617284


<2025x12 sparse matrix of type '<class 'numpy.int64'>'
	with 4237 stored elements in List of Lists format>

In [ ]:
test_original = pd.read_csv('test.csv')

X_final_test = test_original["Review"]
# y = np.asarray(aspects_df[test_original.columns[2:]])
# y = aspects_df[aspects_df.columns[2:]]

In [ ]:
# vetorizar = TfidfVectorizer(max_features=3000, max_df=0.85)
# vetorizar.fit(X_final_test)

X_test_final = vetorizar.transform(X_final_test)

In [ ]:
predicted_1 = mlknn_classifier.predict(X_test_final)

# print(accuracy_score(y_test, predicted))
# print(hamming_loss(y_test, predicted))

In [ ]:
print(predicted_1.toarray())

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 1 0 1]
 [0 0 0 ... 0 1 1]]


In [ ]:
# predicted_1
df = pd.DataFrame(predicted_1.toarray(), columns = ['Components', 'Delivery and Customer Support' ,
                                                    'Design and Aesthetics', 'Dimensions', 'Features', 
                                                    'Functionality', 'Installation', 'Material', 'Price', 'Quality', 'Usability', 'Polarity' ])

# print(df)

df.to_csv("submission_3.csv", index=False)

In [ ]:
from google.colab import files
uploaded = files.download("submission_3.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
model = LinearSVC().fit(X_train_tfidf, np.array(y_train))

ValueError: ignored

In [ ]:
classifier_LR = LogisticRegression()

X_train_tfidf = X_train_tfidf.reshape(-1, 1)
y_train=y_train.reshape(-1,1) 
classifier_LR.fit(X_train_tfidf, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


ValueError: ignored

In [ ]:
new_sentences = ["I like the food but I hate the place"]
new_sentence_tfidf = vetorizar.transform(new_sentences)

predicted_sentences = mlknn_classifier.predict(new_sentence_tfidf)
print(predicted_sentences.toarray())

In [ ]:
predicted_train = classifier_LR.predict(X_test_tfidf)

print(accuracy_score(y_test, predicted_train))
print(hamming_loss(y_test, predicted_train))

predicted_train

In [ ]:
predicted_LR = classifier_LR.predict(X_test_final)

In [ ]:
print(predicted_1.toarray())


df = pd.DataFrame(predicted_1.toarray(), columns = ['Components', 'Delivery and Customer Support' ,
                                                    'Design and Aesthetics', 'Dimensions', 'Features', 
                                                    'Functionality', 'Installation', 'Material', 'Price', 'Quality', 'Usability', 'Polarity' ])

# print(df)

df.to_csv("submission_4.csv", index=False)

In [ ]:
from google.colab import files
uploaded = files.download("submission_4.csv")